In [1]:
# Task 1 
import numpy as np

zomato = np.array([4.5, 4.0, 3.5, 5.0, 4.2])
swiggy = np.array([4.0, 3.8, 4.3, 4.6, 3.9])

combined = np.concatenate((zomato, swiggy))

print("Combined ratings:", combined)

Combined ratings: [4.5 4.  3.5 5.  4.2 4.  3.8 4.3 4.6 3.9]


In [2]:
# Task 2 
import numpy as np

post1 = np.array([100, 120, 150, 130, 140, 160, 180])
post2 = np.array([200, 220, 210, 250, 230, 240, 260])
post3 = np.array([80, 90, 100, 110, 95, 105, 120])

weekly_likes = np.vstack((post1, post2, post3))

print("Weekly likes:")
print(weekly_likes)



Weekly likes:
[[100 120 150 130 140 160 180]
 [200 220 210 250 230 240 260]
 [ 80  90 100 110  95 105 120]]


In [3]:
# Task 3 
import numpy as np

product_ids = np.array([
    101, 102, 103, 104, 105, 106,
    107, 108, 109, 110, 111, 112
])

parts = np.array_split(product_ids, 5)

for i, part in enumerate(parts, 1):
    print("Part", i, ":", part)
    print("Shape:", part.shape)

Part 1 : [101 102 103]
Shape: (3,)
Part 2 : [104 105 106]
Shape: (3,)
Part 3 : [107 108]
Shape: (2,)
Part 4 : [109 110]
Shape: (2,)
Part 5 : [111 112]
Shape: (2,)


In [4]:
# Task 4
import numpy as np

chat = np.array([
    [10, 12, 15, 20, 18, 22, 25],
    [5, 8, 7, 10, 9, 12, 11],
    [20, 18, 22, 25, 24, 27, 30]
])

new_user = np.array([[8, 10, 12, 9, 11, 13, 15]])

chat = np.insert(chat, 1, new_user, axis=0)

print("After adding new user:")
print(chat)

total_messages = np.sum(chat, axis=1)
least_user = np.argmin(total_messages)

chat = np.delete(chat, least_user, axis=0)

print("\nAfter removing user with least messages:")
print(chat)

After adding new user:
[[10 12 15 20 18 22 25]
 [ 8 10 12  9 11 13 15]
 [ 5  8  7 10  9 12 11]
 [20 18 22 25 24 27 30]]

After removing user with least messages:
[[10 12 15 20 18 22 25]
 [ 8 10 12  9 11 13 15]
 [20 18 22 25 24 27 30]]


In [5]:
# Task 5
import numpy as np

views = np.array([1000, 2000, 3000, 4000, 5000])

view_array = views.view()
copy_array = views.copy()

view_array[0] = 9999
copy_array[0] = 8888

print("Original array:", views)
print("View array:", view_array)
print("Copy array:", copy_array)

Original array: [9999 2000 3000 4000 5000]
View array: [9999 2000 3000 4000 5000]
Copy array: [8888 2000 3000 4000 5000]
