In [1]:
# Task 1
import numpy as np

prices = np.array([199, 299, 399, 499, 599])

print("First price:", prices[0])
print("Last price:", prices[-1])

First price: 199
Last price: 599


In [2]:
# Task 2 
import numpy as np

scores = np.array([
    [45, 50, 55, 60, 65],
    [70, 75, 80, 85, 90],
    [55, 60, 65, 70, 75]
])

result = scores[:, 1:4]

print("Scores for matches 2 to 4:")
print(result)

Scores for matches 2 to 4:
[[50 55 60]
 [75 80 85]
 [60 65 70]]


In [3]:
# Task 3
import numpy as np

ratings = np.array([4.5, 3.8, 4.2, 2.9, 5.0, 3.5])

print("Last three ratings:", ratings[-3:])

Last three ratings: [2.9 5.  3.5]


In [4]:
# Task 4
import numpy as np

numbers = np.arange(1, 21)

print("Every 3rd number starting from the second element:")
print(numbers[1::3])

Every 3rd number starting from the second element:
[ 2  5  8 11 14 17 20]


In [5]:
# Task 5
import numpy as np

prices = np.array([250, 600, 450, 750, 300, 900, 550])

result = prices[prices > 500]

print("Prices greater than 500:", result)

Prices greater than 500: [600 750 900 550]


In [6]:
# Task 6
import numpy as np

scores = np.array([210, 180, 195, 220, 205, 175])

indices = np.where(scores > 200)

print("Indices of scores above 200:", indices[0])

Indices of scores above 200: [0 3 4]
