In [1]:
import numpy as np

likes = np.array([120, 250, 180, 300, 150, 220, 275])

print("ndim:", likes.ndim)
print("shape:", likes.shape)
print("size:", likes.size)
print("dtype:", likes.dtype)
print("itemsize:", likes.itemsize)
print("nbytes:", likes.nbytes)

ndim: 1
shape: (7,)
size: 7
dtype: int64
itemsize: 8
nbytes: 56


In [2]:
import numpy as np

steps = np.array([
    [5000, 7000],
    [6000, 8000],
    [5500, 7500],
    [6500, 8500],
    [7000, 9000]
])

print("Original 2D array:")
print(steps)

one_d = steps.reshape(10)
print("\n1D array:")
print(one_d)

two_d = one_d.reshape(5, 2)
print("\nBack to 2D array:")
print(two_d)

Original 2D array:
[[5000 7000]
 [6000 8000]
 [5500 7500]
 [6500 8500]
 [7000 9000]]

1D array:
[5000 7000 6000 8000 5500 7500 6500 8500 7000 9000]

Back to 2D array:
[[5000 7000]
 [6000 8000]
 [5500 7500]
 [6500 8500]
 [7000 9000]]


In [3]:
import numpy as np

prices = np.array([120, 250, 80, 150, 300, 90, 200, 175, 110, 350, 60, 225])

print("Original array:")
print(prices)

# ravel() returns a flattened array
ravel_array = prices.ravel()
print("\nUsing ravel():")
print(ravel_array)

# flatten() also returns a flattened array
flatten_array = prices.flatten()
print("\nUsing flatten():")
print(flatten_array)

# resize() changes the shape of the original array
resize_array = prices.copy()
resize_array.resize(3, 4)
print("\nUsing resize():")
print(resize_array)

Original array:
[120 250  80 150 300  90 200 175 110 350  60 225]

Using ravel():
[120 250  80 150 300  90 200 175 110 350  60 225]

Using flatten():
[120 250  80 150 300  90 200 175 110 350  60 225]

Using resize():
[[120 250  80 150]
 [300  90 200 175]
 [110 350  60 225]]


In [4]:
import numpy as np

playlist = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [12, 22, 32]
])

print("Original array:")
print(playlist)

print("\nUsing T:")
print(playlist.T)

print("\nUsing np.transpose():")
print(np.transpose(playlist))

Original array:
[[10 20 30]
 [15 25 35]
 [12 22 32]]

Using T:
[[10 15 12]
 [20 25 22]
 [30 35 32]]

Using np.transpose():
[[10 15 12]
 [20 25 22]
 [30 35 32]]


In [5]:
import numpy as np

ratings = np.array([4, 5, 3, 4, 2, 5, 4, 3, 5, 2, 4, 5, 3, 4, 5])

print("Original 1D array:")
print(ratings)

three_by_five = ratings.reshape(3, 5)
print("\n3x5 array:")
print(three_by_five)

back_to_1d = three_by_five.flatten()
print("\nBack to 1D:")
print(back_to_1d)

Original 1D array:
[4 5 3 4 2 5 4 3 5 2 4 5 3 4 5]

3x5 array:
[[4 5 3 4 2]
 [5 4 3 5 2]
 [4 5 3 4 5]]

Back to 1D:
[4 5 3 4 2 5 4 3 5 2 4 5 3 4 5]
